#!/usr/bin/python3.6

""" Generate and execute commands to reduce the raw uGMRT data into TIMER format.

    Developers: Abhimanyu Susobhanan, Yogesh Maan
"""

import sys
import os
import numpy as np
import datetime

"""
    Option to write the pipeline logs to a file. 
    The output will be written to $PWD/pinta.log . 
"""
if '--log-to-file' in sys.argv:
    now = datetime.datetime.now().strftime('%Y%m%dT%H%M%S')
    logfile = 'pinta.{}.log'.format(now)
    print('Output will be written to', logfile)
    sys.stdout = open(logfile, 'w') 

import pintautils as utils
import pintaexec as pexec
from pintasession import session

for idx, item in enumerate(session.pipeline_items):

    pexec.setup_input_ln(session, item)
    
    if session.run_gptool:
        utils.copy_gptool_in(session.gptool_in_dir, session.working_dir, item.intfreq)
        pexec.gptool_branch(session, item)
    else:
        pexec.norfix_branch(session, item)
    
    if session.run_rficlean:
        #rfic_hdrfilename = "{}/{}-{}-ttemp-gm.info".format(session.working_dir, item.jname, item.idx)
        utils.make_rficlean_hdrfile(item.rfic_hdrfilename, item.jname, item.freq, item.nchan, item.chanwidth, item.tsmpl, item.sideband)
        os.system('ls -l *.info')
        pexec.rficlean_branch(session, item)

    if session.retain_aux:
        utils.move_aux_files(session, item)
    else:
        utils.remove_aux_files(session, item)
        
    pexec.remove_input_ln(session, item)

